# Avatar Generation Settings

# Bonk settings
bonk:
  overlay: "./img_temps/bonk_clear.png"
  target_size: 250
  position:
    x: 368
    y: 126
    
explosion:
  overlay: "./img_temps/explosion_clear.gif"
